# coding: utf-8

"""
    SwiftAI - user service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from users_client.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_change_user_email_users_user_id_change_email_post(self) -> None:
        """Test case for change_user_email_users_user_id_change_email_post

        Change User Email
        """
        pass

    def test_change_user_password_users_user_id_change_password_post(self) -> None:
        """Test case for change_user_password_users_user_id_change_password_post

        Change User Password
        """
        pass

    def test_create_user_users_post(self) -> None:
        """Test case for create_user_users_post

        Create User
        """
        pass

    def test_get_user_by_id_users_user_id_get(self) -> None:
        """Test case for get_user_by_id_users_user_id_get

        Get User By Id
        """
        pass

    def test_get_users_users_get(self) -> None:
        """Test case for get_users_users_get

        Get Users
        """
        pass

    def test_login_user_users_login_post(self) -> None:
        """Test case for login_user_users_login_post

        Login User
        """
        pass

    def test_register_user_users_user_id_register_post(self) -> None:
        """Test case for register_user_users_user_id_register_post

        Register User
        """
        pass

    def test_update_user_users_user_id_put(self) -> None:
        """Test case for update_user_users_user_id_put

        Update User
        """
        pass


if __name__ == '__main__':
    unittest.main()
