# coding: utf-8

"""
    SwiftAI - user service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from users_client.models.user_schema_update import UserSchemaUpdate

class TestUserSchemaUpdate(unittest.TestCase):
    """UserSchemaUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserSchemaUpdate:
        """Test UserSchemaUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserSchemaUpdate`
        """
        model = UserSchemaUpdate()
        if include_optional:
            return UserSchemaUpdate(
                surname = '',
                name = '',
                domain = ''
            )
        else:
            return UserSchemaUpdate(
        )
        """

    def testUserSchemaUpdate(self):
        """Test UserSchemaUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
