# coding: utf-8

"""
    SwiftAI - user service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from users_client.models.invite_user_schema_add import InviteUserSchemaAdd

class TestInviteUserSchemaAdd(unittest.TestCase):
    """InviteUserSchemaAdd unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InviteUserSchemaAdd:
        """Test InviteUserSchemaAdd
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InviteUserSchemaAdd`
        """
        model = InviteUserSchemaAdd()
        if include_optional:
            return InviteUserSchemaAdd(
                user_id = '',
                invite_code = ''
            )
        else:
            return InviteUserSchemaAdd(
                user_id = '',
                invite_code = '',
        )
        """

    def testInviteUserSchemaAdd(self):
        """Test InviteUserSchemaAdd"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
