# coding: utf-8

"""
    SwiftAI - user service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from users_client.api.roles_api import RolesApi


class TestRolesApi(unittest.TestCase):
    """RolesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RolesApi()

    def tearDown(self) -> None:
        pass

    def test_add_permission_to_role_roles_role_id_permissions_permission_id_post(self) -> None:
        """Test case for add_permission_to_role_roles_role_id_permissions_permission_id_post

        Add Permission To Role
        """
        pass

    def test_add_permissions_to_role_roles_role_id_permissions_post(self) -> None:
        """Test case for add_permissions_to_role_roles_role_id_permissions_post

        Add Permissions To Role
        """
        pass

    def test_create_role_roles_post(self) -> None:
        """Test case for create_role_roles_post

        Create Role
        """
        pass

    def test_delete_role_roles_role_id_delete(self) -> None:
        """Test case for delete_role_roles_role_id_delete

        Delete Role
        """
        pass

    def test_get_role_by_id_roles_role_id_get(self) -> None:
        """Test case for get_role_by_id_roles_role_id_get

        Get Role By Id
        """
        pass

    def test_get_roles_roles_get(self) -> None:
        """Test case for get_roles_roles_get

        Get Roles
        """
        pass

    def test_remove_permission_to_role_roles_role_id_permissions_permission_id_delete(self) -> None:
        """Test case for remove_permission_to_role_roles_role_id_permissions_permission_id_delete

        Remove Permission To Role
        """
        pass


if __name__ == '__main__':
    unittest.main()
