# coding: utf-8

"""
    SwiftAI - user service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from users_client.api.permission_api import PermissionApi


class TestPermissionApi(unittest.TestCase):
    """PermissionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PermissionApi()

    def tearDown(self) -> None:
        pass

    def test_create_permission_permissions_post(self) -> None:
        """Test case for create_permission_permissions_post

        Create Permission
        """
        pass

    def test_delete_permission_permissions_permission_id_delete(self) -> None:
        """Test case for delete_permission_permissions_permission_id_delete

        Delete Permission
        """
        pass

    def test_get_permission_by_id_permissions_permission_id_get(self) -> None:
        """Test case for get_permission_by_id_permissions_permission_id_get

        Get Permission By Id
        """
        pass

    def test_get_permissions_permissions_get(self) -> None:
        """Test case for get_permissions_permissions_get

        Get Permissions
        """
        pass


if __name__ == '__main__':
    unittest.main()
