# coding: utf-8

# flake8: noqa
"""
    SwiftAI - User Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from users_client.models.bearer_response import BearerResponse
from users_client.models.detail import Detail
from users_client.models.error_model import ErrorModel
from users_client.models.http_validation_error import HTTPValidationError
from users_client.models.health_check_details_schema import HealthCheckDetailsSchema
from users_client.models.health_check_response import HealthCheckResponse
from users_client.models.invite_user_schema_add import InviteUserSchemaAdd
from users_client.models.pagination_request_permission_schema import PaginationRequestPermissionSchema
from users_client.models.pagination_request_role_schema import PaginationRequestRoleSchema
from users_client.models.pagination_request_user_schema_base import PaginationRequestUserSchemaBase
from users_client.models.permission_schema import PermissionSchema
from users_client.models.permission_schema_add import PermissionSchemaAdd
from users_client.models.result_request import ResultRequest
from users_client.models.role_schema import RoleSchema
from users_client.models.role_schema_add import RoleSchemaAdd
from users_client.models.role_schema_add_permission import RoleSchemaAddPermission
from users_client.models.service_error_pydantic import ServiceErrorPydantic
from users_client.models.status_database import StatusDatabase
from users_client.models.status_redis import StatusRedis
from users_client.models.type_error_enum import TypeErrorEnum
from users_client.models.user_schema_add import UserSchemaAdd
from users_client.models.user_schema_base import UserSchemaBase
from users_client.models.user_schema_change_email import UserSchemaChangeEmail
from users_client.models.user_schema_change_password import UserSchemaChangePassword
from users_client.models.user_schema_login import UserSchemaLogin
from users_client.models.user_schema_register import UserSchemaRegister
from users_client.models.user_schema_update import UserSchemaUpdate
from users_client.models.validation_error import ValidationError
from users_client.models.validation_error_loc_inner import ValidationErrorLocInner
